name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
      - 'dev'
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      env:
        DOTNET_INSTALL_DIR: "./.dotnet"
      with:
        global-json-file: global.json

    - name: Dotnet Restore Workloads
      run: dotnet workload restore

    - name: Dotnet Build
      run: dotnet build -c Release

    - name: Dotnet Publish Browser
      working-directory: src/AvaloniaTetris.Browser
      run: dotnet publish -c Release

    - name: Dotnet Publish win-x64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r win-x64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop.exe /dist/AvaloniaTetris.Desktop.win-x64.exe

    - name: Dotnet Publish win-arm64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r win-arm64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop.exe /dist/AvaloniaTetris.Desktop.win-arm64.exe

    - name: Dotnet Publish linux-x64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r linux-x64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop /dist/AvaloniaTetris.Desktop.linux-x64

    - name: Dotnet Publish linux-arm64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r linux-arm64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop /dist/AvaloniaTetris.Desktop.linux-arm64

    - name: Dotnet Publish osx-x64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r osx-x64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop /dist/AvaloniaTetris.Desktop.macos-x64

    - name: Dotnet Publish osx-arm64
      working-directory: src/AvaloniaTetris.Desktop
      run: dotnet publish -c Release -r osx-arm64 /p:DebugType=None /p:DebugSymbols=false -o /dist

    - name: Rename
      run: mv /dist/AvaloniaTetris.Desktop /dist/AvaloniaTetris.Desktop.osx-arm64

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install Netlify CLI
      run: npm install netlify-cli -g

    - name: Deploy
      run: netlify deploy ${{ (github.ref == 'refs/heads/master' && '--prod') || '' }} --json -d src/AvaloniaTetris.Browser/bin/Release/net8.0/browser-wasm/AppBundle/
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
